version: 2
jobs:
  test:
    working_directory: /tmp/docilater/
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: sudo apt-get install ruby`ruby -e 'puts RUBY_VERSION[/\d+\.\d+/]'`-dev
      - run: sudo gem install bundler
      - run: bundler install
      - run: ruby tests/doall.rb
workflows:
  version: 2
  test:
    jobs:
      - test
