version: 2
jobs:
  test:
    working_directory: /tmp/docilater/
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: sudo gem install bundler
      - run: cd lib
      - run: bundler install
      - run: cd ..
      - run: ruby tests/doall.rb
workflows:
  version: 2
  test:
    jobs:
      - test
